# Generated by Django 4.1.5 on 2023-01-16 22:45

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cpf', models.CharField(db_index=True, help_text='Apenas números', max_length=11, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(error_messages={'unique': 'Esse e-mail já existe.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('dataDeNascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('rendaMensal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
