# Generated by Django 4.1.5 on 2023-01-18 03:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratacaoPlano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dataDaContratacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('susep', models.CharField(max_length=20)),
                ('expiracaoDeVenda', models.DateField()),
                ('valorMinimoAporteInicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valorMinimoAporteExtra', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idadeDeEntrada', models.SmallIntegerField()),
                ('idadeDeSaida', models.SmallIntegerField()),
                ('carenciaDeResgate', models.SmallIntegerField()),
                ('carenciaEntreResgates', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorResgate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idPlano', models.ForeignKey(db_column='idPlano', on_delete=django.db.models.deletion.PROTECT, to='api.contratacaoplano')),
            ],
        ),
        migrations.AddField(
            model_name='contratacaoplano',
            name='idCliente',
            field=models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
        ),
        migrations.AddField(
            model_name='contratacaoplano',
            name='idProduto',
            field=models.ForeignKey(db_column='idProduto', on_delete=django.db.models.deletion.PROTECT, to='api.produto'),
        ),
        migrations.CreateModel(
            name='AporteExtra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valorAporte', models.DecimalField(decimal_places=2, max_digits=12)),
                ('idCliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.PROTECT, to='api.cliente')),
                ('idPlano', models.ForeignKey(db_column='idPlano', on_delete=django.db.models.deletion.PROTECT, to='api.contratacaoplano')),
            ],
        ),
    ]
