# Generated by Django 4.1.5 on 2023-01-19 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contratacaoplano_produto_rename_client_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='carenciaDeResgate',
            new_name='carenciaInicialDeResgate',
        ),
    ]
